### ISSUE TITLE
HA indicates the system is cooling, while it is heating

### ISSUE THREAD

**Issue by ditisdirkdewit** [soundvibe/ha-danfoss#15]
Hi @soundvibe , 

First of all thanks for the add-in, great work. I installed the add-on during summer, when my Danfoss Icon system is primarily cooling, so I was happy to see that this was shown in HA as well.
Currently Danfoss is heating, however it still shows as "cooling" in HA. I checked the MQTT messages that HA received from the Add on, those indicate the mode "cooling", while the system is heating.

Anything i can provide / do to fix this? Thanks!

**Comment by soundvibe** [comment]
Hi,

I don't have cooling in my danfoss system, so I can't test this properly but the way it is implemented in this addon is quite simple - danfoss api reports two flags - `ROOM_HEATINGCOOLINGSTATE` and `ROOM_COOLINGENABLED`. If `ROOM_COOLINGENABLED` is true, then `ROOM_HEATINGCOOLINGSTATE` reports `cooling` , otherwise it reports `heating`.  So maybe this cooling enabled option is turned on somewhere.

**Comment by ditisdirkdewit** [comment]
Thanks for the quick response.

I believe coolingenabled is not indicating whether the thermostat is cooling at the moment. But it indicates if you have the Cooling option enabled in your thermostat. As described here: [](https://assets.danfoss.com/documents/36435/AN28953970588601-010201.pdf).

> _Settings on thermostat
Excluding rooms from cooling: To exclude a room from cooling - typically in bathrooms where cooling would be uncomfortable - go to thermostat and set menu to . See Thermostat Installation Guide for further information._

Just tested to confirm. I disabled the coolingmode in one of my thermostats and now - while danfoss is heating - HA indeed indicates it is heating (instead of cooling).

**Comment by soundvibe** [comment]
> I believe coolingenabled is not indicating whether the thermostat is cooling at the moment. But it indicates if you have the Cooling option enabled in your thermostat. As described here: .

Yes, coolingenabled itself only indicates if cooling is enabled but we use it with conjunction with `ROOM_HEATINGCOOLINGSTATE` because danfoss api doesn't report specifically which mode(heating or cooling) is on (ROOM_HEATINGCOOLINGSTATE reports that either heating or cooling is on/off).

**Comment by ditisdirkdewit** [comment]
That's a shame it is not reflected in the API. Danfoss does indicate it in their own app. If heating you see the red arrows going upward. And if cooling you blue arrows going downward. I know the cooling/heating mode is not a per room setting but for the whole system. Could it be this is indicated in one of the RAIL class values? " int RAIL_INPUTHEATORCOOL"?

**Comment by DrTomek** [comment]
Hi all, as I also use cooling and heating, I have checked what is going on with my system.
And indeed it shows cooling while heating. But stange thing I noticed is one thermostat shows cooling while other one shows heating. (In Danfoss App both heating and both are thermostats in bathroom with cooling is disabled on them).
![1](https://github.com/user-attachments/assets/5b29e11b-b4ba-4697-84e1-15412e92ac24)
![2](https://github.com/user-attachments/assets/c494035a-5cd3-4af0-9387-d63d31711e67)
![IMG_2177](https://github.com/user-attachments/assets/6b147ce7-ad28-4580-b90a-0af5c10718b2)

**Comment by ditisdirkdewit** [comment]
I decided to fix it differently  as the COOLINGENABLED parameter is in my view not a good parameter to identify if the system is cooling or heating. I created an automation that switches a boolean helper(input_boolean.verwarmen_of_koelen) to heating or cooling based on the data from my heatpump. 

In the climate template I added the following if statement for "hvac_mode_template" (not using MQTT anymore). Hopes it helps anyone.

`hvac_mode_template:` "{% if state_attr('sensor.danfoss_0_temperature', 'mode') == 'cool' and states('input_boolean.verwarmen_of_koelen') == 'off' %} heat {% elif state_attr('sensor.danfoss_0_temperature', 'mode') == 'cool' and states('input_boolean.verwarmen_of_koelen') == 'on' %} cool {% elif state_attr('sensor.danfoss_0_temperature', 'mode') == 'off' %} off {% endif %}"

**Comment by soundvibe** [comment]
@ditisdirkdewit  I've pushed very small addon update. It now logs `RAIL_INPUTHEATORCOOL` and `ROOM_HEATINGCOOLINGCONFIGURATION` packets. Would be great if you could test what values are you getting when these heating/cooling modes are changing. In order to see these log messages, `debug` logging should be set in addon configuration.

**Comment by ditisdirkdewit** [comment]
Thanks @soundvibe, I'll try to test it asap.

**Comment by ditisdirkdewit** [comment]
I tried it quickly, but don't see anything in the debug? or info logging on RAIL_INPUTHEATORCOOL or ROOM_HEATINGCOOLINGCONFIGURATION? any suggestion what parameters I should search for?

**Comment by ditisdirkdewit** [comment]
Just thinking out loud. shouldn't this piece of code be included in the "IconMasterHandler" instead of IconRoomHandler".
```
            case RAIL_INPUTHEATORCOOL:
                logger.info("rail input heat or cool={}", pkt.getByte());
                break;
```

**Comment by soundvibe** [comment]
> Just thinking out loud. shouldn't this piece of code be included in the "IconMasterHandler" instead of IconRoomHandler".
> 
> ```
>             case RAIL_INPUTHEATORCOOL:
>                 logger.info("rail input heat or cool={}", pkt.getByte());
>                 break;
> ```

Yes, fixed in the new version.

**Comment by ditisdirkdewit** [comment]
That's it! When switching to cooling the value changes to 1. And switching back to heating the value is 0 again:
```

21:36:09.639 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
21:37:09.469 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
21:38:09.605 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
21:38:33.058 [SDG socket thread.1] INFO  n.s.h.d.protocol.IconMasterHandler - rail input heat or cool=1
21:39:09.485 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
21:39:39.563 [SDG socket thread.1] INFO  n.s.h.d.protocol.IconMasterHandler - rail input heat or cool=0
```

**Comment by soundvibe** [comment]
> That's it! When switching to cooling the value changes to 1. And switching back to heating the value is 0 again:
> 
> ```
> 
> 21:36:09.639 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
> 21:37:09.469 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
> 21:38:09.605 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
> 21:38:33.058 [SDG socket thread.1] INFO  n.s.h.d.protocol.IconMasterHandler - rail input heat or cool=1
> 21:39:09.485 [] INFO  net.soundvibe.hasio.Bootstrapper - sensors updated successfully
> 21:39:39.563 [SDG socket thread.1] INFO  n.s.h.d.protocol.IconMasterHandler - rail input heat or cool=0
> ```

That's nice! Now I need to update the code accordingly.

**Comment by soundvibe** [comment]
@ditisdirkdewit  I've pushed a new update, please test it and let me know if it works as expected. I think it should work but it's late now and I'm a bit tired.

**Comment by ditisdirkdewit** [comment]
Thanks @soundvibe! it works as it should now, appreciate you fixing this quickly
