### ISSUE TITLE
I have a few ideas for improvements/issues

### ISSUE THREAD

**Issue by Andreasjkoch** [soundvibe/ha-danfoss#9]
Hi.
First of all I want to thank you very much for this addon. Previously I have been using an openHAB installation with a Danfoss Icon "binding" installed. I then created a script in openHAB to expose the thermostats to HomeAssistant using MQTT. Now that I have tried "the openHAB version" of this, I do have a few ideas for improvements/issues regarding this addon.

- Would it be possible to improve the polling rate for the thermostats? When I, using the Danfoss app change a target temperature, it reflects in openHAB in about 2 seconds, while your addon takes up to a minute.
- Would it be possible to change the "high" and "low" values of the Climate entities? In my mind it would make more sense to display the "At home" and "Away" target temperatures rather than the thermostats max and min temperatures. Please see the attached photos, for more context.
![billede](https://github.com/soundvibe/ha-danfoss/assets/47931272/3f4ccf43-9530-456c-b9ed-585423e3e1ab)
![billede](https://github.com/soundvibe/ha-danfoss/assets/47931272/20e14563-0c3b-41dc-a28a-ae926e1cd809)
- Also, I am unable to actually set the temperature with this addon. It does create the "set" MQTT topic, but doesn't do anything else than that. (This is with the automatic MQTT creation of the Climate entities)
![billede](https://github.com/soundvibe/ha-danfoss/assets/47931272/9b4b28ab-c339-48d7-983a-342cad830013)

_The openHAB binding, that I am using can be found [here](https://github.com/Sonic-Amiga/org.openhab.binding.devireg)_

**Comment by soundvibe** [comment]
> * Would it be possible to improve the polling rate for the thermostats? When I, using the Danfoss app change a target temperature, it reflects in openHAB in about 2 seconds, while your addon takes up to a minute.

Currently, the polling internal is in minutes in addon config, but it could be easily changed to seconds. I think I can do this some time later.

> * Would it be possible to change the "high" and "low" values of the Climate entities? In my mind it would make more sense to display the "At home" and "Away" target temperatures rather than the thermostats max and min temperatures. Please see the attached photos, for more context.

Yes, it's definitely possible to do. Do other climate integrations work in the same way?

> * Also, I am unable to actually set the temperature with this addon. It does create the "set" MQTT topic, but doesn't do anything else than that. (This is with the automatic MQTT creation of the Climate entities)
billede

It may take up to a minute for a set temperature to be applied I think (reducing polling internal might help with this as well). Also, it is setting temperature based on the current room mode, so f.i. if it is set to `away`, it will try to set away temperature.

**Comment by Andreasjkoch** [comment]
> Currently, the polling interval is in minutes in addon config, but it could be easily changed to seconds. I merged new update so you can configure it now.

Nice, thank you very much! :)

> Yes, it's definitely possible to do. Do other climate integrations work in the same way?

I honestly don't know, and I don't really have anything to test it with. However I do personally think that it makes more sense showing the target temperatures (at least the two common ones; home and away) on the graph, rather than showing the min and max temperatures that the thermostat is allowed to be set to, as these should never be reached anyway. Doing it this way, also allows the user to see whether or not the heating is actually reaching the target temperatures and at what time(s) of the day is may have failed to do so. 

> It may take up to a minute for a set temperature to be applied I think (reducing polling interval might help with this as well). 

I think there is something more to this than just having to wait. I have have tried waiting 5 minutes or so, and the change is never reflected in the app, even while having a polling interval of 2 seconds. It also seems a bit weird to me, that as soon as I close and reopen the climate entity dialog after having changed the target temperature, it immediately goes back to what it was before. I have attempted to create a GIF that illustrates what I mean by this. I am of course reopening the same climate entity as the one I just changed the temperature in :). Also, there are no logs indicating any kind of error.

![clideo_editor_e91e9e9eb96b433fbeb9af116ae341ae](https://github.com/soundvibe/ha-danfoss/assets/47931272/1168dff5-9cbe-4200-a0b2-78377e2620de)

_I don't know if this gif helps to understand what I mean, but I tried_ 😆

**Comment by soundvibe** [comment]
> > Currently, the polling interval is in minutes in addon config, but it could be easily changed to seconds. I merged new update so you can configure it now.
> 
> Nice, thank you very much! :)
> 
> > Yes, it's definitely possible to do. Do other climate integrations work in the same way?
> 
> I honestly don't know, and I don't really have anything to test it with. However I do personally think that it makes more sense showing the target temperatures (at least the two common ones; home and away) on the graph, rather than showing the min and max temperatures that the thermostat is allowed to be set to, as these should never be reached anyway. Doing it this way, also allows the user to see whether or not the heating is actually reaching the target temperatures and at what time(s) of the day is may have failed to do so.
> 
> > It may take up to a minute for a set temperature to be applied I think (reducing polling interval might help with this as well).
> 
> I think there is something more to this than just having to wait. I have have tried waiting 5 minutes or so, and the change is never reflected in the app, even while having a polling interval of 2 seconds. It also seems a bit weird to me, that as soon as I close and reopen the climate entity dialog after having changed the target temperature, it immediately goes back to what it was before. I have attempted to create a GIF that illustrates what I mean by this. I am of course reopening the same climate entity as the one I just changed the temperature in :). Also, there are no logs indicating any kind of error.
> 
> ![clideo_editor_e91e9e9eb96b433fbeb9af116ae341ae](https://private-user-images.githubusercontent.com/47931272/316993305-1168dff5-9cbe-4200-a0b2-78377e2620de.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODQwMDksIm5iZiI6MTcxMTQ4MzcwOSwicGF0aCI6Ii80NzkzMTI3Mi8zMTY5OTMzMDUtMTE2OGRmZjUtOWNiZS00MjAwLWEwYjItNzgzNzdlMjYyMGRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwMDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDlkNGM2OWUyNDE2ZTM5NjIzNTZiOTZjYzdlNTE1NGQ4NjM0ZjRlOGUzZDRlZGM3ZDZmNGZlZjUwODJiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NdXuBV40a_ksu1yn--63eB-vw-ZiFpY49Y1QA849sec) [ ![clideo_editor_e91e9e9eb96b433fbeb9af116ae341ae](https://private-user-images.githubusercontent.com/47931272/316993305-1168dff5-9cbe-4200-a0b2-78377e2620de.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODQwMDksIm5iZiI6MTcxMTQ4MzcwOSwicGF0aCI6Ii80NzkzMTI3Mi8zMTY5OTMzMDUtMTE2OGRmZjUtOWNiZS00MjAwLWEwYjItNzgzNzdlMjYyMGRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwMDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDlkNGM2OWUyNDE2ZTM5NjIzNTZiOTZjYzdlNTE1NGQ4NjM0ZjRlOGUzZDRlZGM3ZDZmNGZlZjUwODJiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NdXuBV40a_ksu1yn--63eB-vw-ZiFpY49Y1QA849sec) ](https://private-user-images.githubusercontent.com/47931272/316993305-1168dff5-9cbe-4200-a0b2-78377e2620de.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODQwMDksIm5iZiI6MTcxMTQ4MzcwOSwicGF0aCI6Ii80NzkzMTI3Mi8zMTY5OTMzMDUtMTE2OGRmZjUtOWNiZS00MjAwLWEwYjItNzgzNzdlMjYyMGRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwMDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDlkNGM2OWUyNDE2ZTM5NjIzNTZiOTZjYzdlNTE1NGQ4NjM0ZjRlOGUzZDRlZGM3ZDZmNGZlZjUwODJiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NdXuBV40a_ksu1yn--63eB-vw-ZiFpY49Y1QA849sec) [ ](https://private-user-images.githubusercontent.com/47931272/316993305-1168dff5-9cbe-4200-a0b2-78377e2620de.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODQwMDksIm5iZiI6MTcxMTQ4MzcwOSwicGF0aCI6Ii80NzkzMTI3Mi8zMTY5OTMzMDUtMTE2OGRmZjUtOWNiZS00MjAwLWEwYjItNzgzNzdlMjYyMGRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDIwMDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDlkNGM2OWUyNDE2ZTM5NjIzNTZiOTZjYzdlNTE1NGQ4NjM0ZjRlOGUzZDRlZGM3ZDZmNGZlZjUwODJiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NdXuBV40a_ksu1yn--63eB-vw-ZiFpY49Y1QA849sec)
> 
> _I don't know if this gif helps to understand what I mean, but I tried_ 😆

Could you try changing the target temperature in HA, and have Danfoss app opened at the same time? Is the new value updating in the Danfoss app as well? To me it is updated instantly in the Danfoss app, but the thermostat in HA is lagging behind if you reopen it (I think because of mqtt updates and polling interval)

**Comment by Andreasjkoch** [comment]
> Could you try changing the target temperature in HA, and have Danfoss app opened at the same time? Is the new value updating in the Danfoss app as well? To me it is updated instantly in the Danfoss app, but the thermostat in HA is lagging behind if you reopen it (I think because of mqtt updates and polling interval)

I forgot to mention it, but I have had the app open while I attempting to change it. It doesn't change at all in the app.

**Comment by Andreasjkoch** [comment]
I think I have figured out the issue. I attempted to restart to addon, and then it worked. The issue seems to occur if you attempt to select the thermostat mode, which you are of my understanding, not supposed to do. It will then fall back to the current mode after which you can no longer change the target temperature.
